# Site Build Settings

future: false

exclude:
  - dependencies/

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag] # jekyll-paginate

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		        'John Moïse'
description:        'A blog.'
url:                https://johnmoise.xyz
author:             'John Moïse'

  # RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

